# Generated by Django 4.0.4 on 2022-05-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('aadharcard', models.FileField(upload_to='')),
                ('pancard', models.FileField(upload_to='')),
                ('salaryslips', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
