# Generated by Django 4.0.4 on 2022-05-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilescreen', '0003_data_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='phonenumber',
            new_name='CTC',
        ),
    ]
