# Generated by Django 4.0.4 on 2022-05-10 03:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('tenture', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('', 'Select'), ('IT employee', 'Goverment staff'), ('Business', 'IT employee'), ('Startup', 'Business')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('interest', models.IntegerField()),
                ('income', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('<500000', '<500000'), ('500000-1000000', '500000-1000000'), ('>1000000', '>1000000')], max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
